# Generated by Django 5.2.6 on 2026-01-09 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bucket_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('allowed_mime_types', models.JSONField(blank=True, default=list)),
                ('max_file_size', models.BigIntegerField(blank=True, help_text='Max file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storage_buckets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path within bucket', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('public_url', models.URLField(blank=True, null=True)),
                ('signed_url', models.URLField(blank=True, null=True)),
                ('signed_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crypto_access.storagebucket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['bucket', 'file_path'], name='uploaded_fi_bucket__bb1542_idx'), models.Index(fields=['uploaded_by'], name='uploaded_fi_uploade_4163f5_idx'), models.Index(fields=['file_type'], name='uploaded_fi_file_ty_206d78_idx')],
            },
        ),
    ]
