# Generated by Django 5.2.6 on 2026-01-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0002_storagebucket_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn tài khoản'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='Trạng thái tài khoản'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attribute_doc_id',
            field=models.CharField(blank=True, help_text='Reference to user_attributes collection (BM4)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('data_owner', 'Data Owner'), ('data_user', 'Data User'), ('auditor', 'Auditor'), ('guest', 'Guest')], default='data_user', max_length=20, verbose_name='Loại người dùng'),
        ),
    ]
