# Generated by Django 5.2.6 on 2026-01-09 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0003_userprofile_account_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Attribute name (e.g., 'department', 'role')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for UI', max_length=100)),
                ('data_type', models.CharField(choices=[('enum', 'Enumeration'), ('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', max_length=20)),
                ('allowed_values', models.JSONField(blank=True, help_text='List of allowed values for enum type', null=True)),
                ('default_value', models.CharField(blank=True, help_text='Default value for this attribute', max_length=255, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this attribute is required for all users')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Attribute Definition',
                'verbose_name_plural': 'Attribute Definitions',
                'db_table': 'crypto_attribute_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique code (e.g., 'super_admin', 'data_owner')", max_length=30, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Super Admin')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this user type')),
                ('permissions', models.JSONField(default=list, help_text="List of permission codes (e.g., ['user_management', 'file_management'])")),
                ('is_system', models.BooleanField(default=False, help_text='System types cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'db_table': 'crypto_user_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('data_owner', 'Data Owner'), ('data_user', 'Data User'), ('auditor', 'Auditor'), ('guest', 'Guest')], default='data_user', max_length=20, verbose_name='Loại người dùng (legacy)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='crypto_access.usertype', verbose_name='Loại người dùng'),
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='Attribute value', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('expired', 'Expired')], default='active', max_length=20)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this attribute becomes effective')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date when this attribute expires (null = never)', null=True)),
                ('version', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_values', to='crypto_access.attributedefinition')),
                ('updated_by', models.ForeignKey(help_text='Admin who last updated this attribute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abac_attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Attribute',
                'verbose_name_plural': 'User Attributes',
                'db_table': 'crypto_user_attributes',
                'ordering': ['user', 'attribute__name'],
                'unique_together': {('user', 'attribute')},
            },
        ),
    ]
