# Generated by Django 5.2.6 on 2026-01-09 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0005_seed_default_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Policy name for identification', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this policy does')),
                ('subject_condition', models.TextField(help_text="ABAC condition expression using r.sub attributes. Example: r.sub.department == 'it'")),
                ('resource', models.CharField(choices=[('document', 'Document'), ('key', 'Encryption Key'), ('user', 'User Management'), ('policy', 'Policy Management'), ('attribute', 'Attribute Management'), ('audit', 'Audit Logs'), ('*', 'All Resources')], help_text='Resource this policy applies to', max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write/Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('download', 'Download'), ('encrypt', 'Encrypt'), ('decrypt', 'Decrypt'), ('manage', 'Full Management'), ('*', 'All Actions')], help_text='Action this policy permits/denies', max_length=50)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', help_text='Whether to allow or deny this access', max_length=10)),
                ('priority', models.IntegerField(default=100, help_text='Policy priority (lower number = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is active')),
                ('created_by', models.ForeignKey(help_text='Admin who created this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Policy',
                'verbose_name_plural': 'Access Policies',
                'db_table': 'crypto_access_policies',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
