# Generated by Django 5.2.6 on 2026-01-25 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0006_add_access_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_id', models.CharField(help_text='Unique log ID (e.g., log_20250908_143052_001)', max_length=100, unique=True)),
                ('resource_type', models.CharField(help_text='Type of resource (document, key, user, etc.)', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the specific resource', max_length=255, null=True)),
                ('action', models.CharField(help_text='Action attempted (read, write, download, etc.)', max_length=50)),
                ('result', models.CharField(choices=[('allow', 'Allowed'), ('deny', 'Denied'), ('error', 'Error')], help_text='Result of access decision', max_length=20)),
                ('policies_evaluated', models.JSONField(default=list, help_text='List of policy names that were evaluated')),
                ('policies_matched', models.JSONField(default=list, help_text='List of policies that matched the request')),
                ('user_attributes', models.JSONField(default=dict, help_text="User's ABAC attributes at time of access")),
                ('environment_attributes', models.JSONField(default=dict, help_text='Environment context (IP, time, device, etc.)')),
                ('request_path', models.CharField(blank=True, help_text='Full request path', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if access check failed', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the access request occurred')),
                ('user', models.ForeignKey(help_text='User who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'crypto_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='crypto_acce_user_id_9bfe14_idx'), models.Index(fields=['resource_type', 'action'], name='crypto_acce_resourc_b0403e_idx'), models.Index(fields=['result', 'timestamp'], name='crypto_acce_result_0feb84_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeyRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revocation_id', models.CharField(help_text='Unique revocation ID (e.g., rev_22520001_20250910)', max_length=100, unique=True)),
                ('key_id', models.CharField(help_text='ID of the revoked key', max_length=100)),
                ('key_version', models.IntegerField(default=1, help_text='Version of the revoked key')),
                ('reason', models.CharField(choices=[('attribute_change', 'Thuộc tính người dùng thay đổi'), ('security_breach', 'Vi phạm bảo mật'), ('account_termination', 'Chấm dứt tài khoản'), ('key_expiration', 'Khóa hết hạn'), ('admin_revoke', 'Admin thu hồi thủ công'), ('key_rotation', 'Luân chuyển khóa định kỳ')], help_text='Reason for key revocation', max_length=30)),
                ('reason_detail', models.TextField(blank=True, help_text='Additional details about revocation reason')),
                ('old_attributes', models.JSONField(default=dict, help_text='User attributes before change (for attribute_change reason)')),
                ('new_attributes', models.JSONField(default=dict, help_text='User attributes after change')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('revoked', 'Đã thu hồi'), ('reissued', 'Đã cấp khóa mới'), ('cancelled', 'Đã hủy')], default='pending', help_text='Current status of revocation', max_length=20)),
                ('new_key_id', models.CharField(blank=True, help_text='ID of newly issued key (if applicable)', max_length=100, null=True)),
                ('revoked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the key was revoked')),
                ('reissued_at', models.DateTimeField(blank=True, help_text='When new key was issued', null=True)),
                ('revoked_by', models.ForeignKey(help_text='Admin who performed the revocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revocations_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose key is revoked', on_delete=django.db.models.deletion.CASCADE, related_name='key_revocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Revocation',
                'verbose_name_plural': 'Key Revocations',
                'db_table': 'crypto_key_revocations',
                'ordering': ['-revoked_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='crypto_key__user_id_e227b1_idx'), models.Index(fields=['key_id'], name='crypto_key__key_id_8b3748_idx'), models.Index(fields=['revoked_at'], name='crypto_key__revoked_9fe702_idx')],
            },
        ),
    ]
