# Generated by Django 5.2.6 on 2026-01-25 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0007_add_audit_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(blank=True, help_text="Folder path for folder-level policies (e.g., 'hr/', 'finance/reports/')", max_length=500)),
                ('target_type', models.CharField(choices=[('file', 'Single File'), ('folder', 'Folder (recursive)')], default='file', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about why this policy was assigned')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_file_policies', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(help_text='Storage bucket for folder policies', on_delete=django.db.models.deletion.CASCADE, related_name='folder_policies', to='crypto_access.storagebucket')),
                ('granted_users', models.ManyToManyField(blank=True, help_text='Users with explicit access to this file (bypasses ABAC)', related_name='granted_file_access', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='The access policy to apply to this file/folder', on_delete=django.db.models.deletion.CASCADE, related_name='file_assignments', to='crypto_access.accesspolicy')),
                ('uploaded_file', models.ForeignKey(blank=True, help_text='Link to specific file (for file targets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='crypto_access.uploadedfile')),
            ],
            options={
                'verbose_name': 'File Access Policy',
                'verbose_name_plural': 'File Access Policies',
                'db_table': 'file_access_policies',
                'ordering': ['-assigned_at'],
                'unique_together': {('folder_path', 'bucket', 'policy'), ('uploaded_file', 'policy')},
            },
        ),
    ]
