# Generated by Django 5.2.6 on 2026-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0008_add_file_access_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='cpabe_policy',
            field=models.CharField(blank=True, help_text='Equivalent CP-ABE policy string. Example: (department:it and clearance_level:secret)', max_length=500, null=True),
        ),
    ]
