# Generated by Django 5.2.6 on 2026-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0009_accesspolicy_cpabe_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesspolicy',
            name='folder_path',
            field=models.CharField(blank=True, help_text="Folder path for folder-level policies (e.g., 'hr/', 'finance/reports/')", max_length=500, null=True),
        ),
    ]
