# Generated by Django 5.2.6 on 2026-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0010_alter_fileaccesspolicy_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Unique key for the setting (e.g. ACTION_PERMISSION_MAP)', max_length=255, unique=True)),
                ('value', models.JSONField(help_text='JSON value for this setting')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'crypto_system_settings',
                'ordering': ['key'],
            },
        ),
    ]
