# Generated by Django 5.2.6 on 2026-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0011_systemsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
