# Generated by Django 5.2.6 on 2026-06-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0012_uploadedfile_deleted_at_uploadedfile_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('physical_path', models.CharField(help_text='Actual path in storage (e.g. docs/report_v2.pdf)', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('cpabe_policy', models.TextField(blank=True, help_text='CP-ABE policy string used to encrypt this specific version', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crypto_access.uploadedfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_versions',
                'ordering': ['-version_number'],
                'unique_together': {('file', 'version_number')},
            },
        ),
    ]
