# Generated by Django 5.2.6 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0013_fileversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="public_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="signed_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
