# Generated by Django 5.2.6 on 2026-06-04 11:02

from django.db import migrations

def rename_user_types(apps, schema_editor):
    UserType = apps.get_model('crypto_access', 'UserType')
    
    # Rename data_viewer -> data_user
    try:
        ut2 = UserType.objects.get(code='data_viewer')
        ut2.code = 'data_user'
        ut2.name = 'Data User'
        ut2.description = 'Data User - Only has permission to read and download files according to assigned policies'
        ut2.save()
    except UserType.DoesNotExist:
        pass

def reverse_rename(apps, schema_editor):
    UserType = apps.get_model('crypto_access', 'UserType')
    
    try:
        ut2 = UserType.objects.get(code='data_user')
        ut2.code = 'data_viewer'
        ut2.name = 'Data Viewer'
        ut2.save()
    except UserType.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0014_alter_uploadedfile_public_url_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_user_types, reverse_rename),
    ]
