# Generated by Django 5.2.6 on 2026-06-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0015_rename_usertypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyrevocation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("attribute_change", "User attributes changed"),
                    ("security_breach", "Security breach"),
                    ("account_termination", "Account terminated"),
                    ("key_expiration", "Key expired"),
                    ("admin_revoke", "Admin revoked manually"),
                    ("key_rotation", "Periodic key rotation"),
                ],
                help_text="Reason for key revocation",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="keyrevocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("revoked", "Revoked"),
                    ("reissued", "Key reissued"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of revocation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="account_expiry_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Account Expiry Date"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Activation"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=20,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("data_owner", "Data Owner"),
                    ("data_user", "Data User"),
                    ("auditor", "Auditor"),
                    ("guest", "Guest"),
                ],
                default="data_user",
                max_length=20,
                verbose_name="User Type (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="crypto_access.usertype",
                verbose_name="User Type",
            ),
        ),
    ]
