# Generated by Django 5.2.6 on 2026-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0016_alter_keyrevocation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspolicy",
            name="resource",
            field=models.CharField(
                help_text="Resource this policy applies to", max_length=255
            ),
        ),
    ]
