# Generated by Django 5.2.6 on 2026-06-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0017_alter_accesspolicy_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertype",
            name="permissions",
        ),
    ]
