# Generated by Django 5.2.6 on 2026-06-10 13:38

import crypto_access.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_access', '0018_remove_usertype_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name_hash',
            field=crypto_access.models.fields.BlindIndexField(blank=True, editable=False, help_text='HMAC-SHA3-256 for secure search', max_length=64, source_field='file_name'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='environment_attributes',
            field=crypto_access.models.fields.EncryptedJSONField(default=dict, help_text='Environment context (IP, time, device, etc.) (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_attributes',
            field=crypto_access.models.fields.EncryptedJSONField(default=dict, help_text="User's ABAC attributes at time of access (Encrypted)"),
        ),
        migrations.AlterField(
            model_name='keyrevocation',
            name='new_attributes',
            field=crypto_access.models.fields.EncryptedJSONField(default=dict, help_text='User attributes after change (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='keyrevocation',
            name='old_attributes',
            field=crypto_access.models.fields.EncryptedJSONField(default=dict, help_text='User attributes before change (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=crypto_access.models.fields.EncryptedCharField(help_text='File name (Encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='metadata',
            field=crypto_access.models.fields.EncryptedJSONField(blank=True, default=dict, help_text='Additional metadata (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='value',
            field=crypto_access.models.fields.EncryptedCharField(help_text='Attribute value (Encrypted)', max_length=500),
        ),
    ]
