# Generated by Django 5.2.6 on 2026-06-10 14:06

import crypto_access.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0019_uploadedfile_file_name_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file_path_hash",
            field=crypto_access.models.fields.BlindIndexField(
                blank=True,
                editable=False,
                help_text="HMAC-SHA3-256 for secure path search",
                max_length=64,
                null=True,
                source_field="file_path",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_path",
            field=crypto_access.models.fields.EncryptedCharField(
                help_text="Path within bucket (Encrypted)", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="public_url",
            field=crypto_access.models.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="signed_url",
            field=crypto_access.models.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
