# Generated by Django 5.2.6 on 2026-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0021_rename_contributor_to_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="log_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA3-256 hash of this log entry",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA3-256 hash of the previous log entry",
                max_length=64,
                null=True,
            ),
        ),
    ]
