# Generated by Django 5.2.6 on 2026-06-12 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0022_accesslog_log_hash_accesslog_previous_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        help_text="JWT Token JTI (ID)", max_length=255, unique=True
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Windows PC, iPhone 13",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Chrome, Firefox",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "os_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Windows 10, iOS",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Country/City from GeoIP",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_active", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Session",
                "verbose_name_plural": "Active Sessions",
                "db_table": "crypto_active_sessions",
                "ordering": ["-last_active"],
            },
        ),
    ]
