# Generated by Django 5.2.6 on 2026-06-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0023_activesession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="user_signature",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded ML-DSA-87 signature from the frontend",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserPublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pqc_public_key",
                    models.TextField(help_text="Base64 encoded ML-DSA-87 Public Key"),
                ),
                (
                    "encrypted_pqc_sk_primary",
                    models.TextField(
                        help_text="Base64 encoded string: [IV (12 bytes)] + [Ciphertext of Secret Key encrypted with WebAuthn PRF]"
                    ),
                ),
                (
                    "encrypted_pqc_sk_recovery",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded string: [IV (12 bytes)] + [Ciphertext of Secret Key encrypted with Argon2 Mnemonic Fallback]",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device/browser name where this key was generated",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this keypair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pqc_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User PQC Public Key",
                "verbose_name_plural": "User PQC Public Keys",
                "db_table": "crypto_user_pki_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fileversion",
            name="signer_public_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the exact public key used to sign this version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_files",
                to="crypto_access.userpublickey",
            ),
        ),
    ]
