# Generated by Django 5.2.6 on 2026-06-19 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0024_fileversion_user_signature_userpublickey_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential_id",
                    models.BinaryField(
                        help_text="Unique credential identifier (raw bytes)",
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(
                        help_text="COSE-encoded public key for signature verification"
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Signature counter for replay attack detection",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Friendly name for the authenticator device",
                        max_length=255,
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authenticator Attestation GUID",
                        max_length=36,
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported transports (usb, nfc, ble, internal, hybrid)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this credential is currently active",
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a synced/backed-up passkey (cross-platform)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this credential",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WebAuthn Credential",
                "verbose_name_plural": "WebAuthn Credentials",
                "db_table": "crypto_webauthn_credentials",
                "ordering": ["-created_at"],
            },
        ),
    ]
