# Generated by Django 5.2.6 on 2026-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0025_webauthncredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="trusted_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="The exact server time when the signature was received",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="tsa_signature",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded ML-DSA-87 signature from the Server/RootCA over (file_hash + user_signature + timestamp)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpublickey",
            name="ca_signature",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded ML-DSA-87 signature from the RootCA over the JSON representation of this key",
                null=True,
            ),
        ),
    ]
