# Generated by Django 5.2.6 on 2026-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0026_fileversion_trusted_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspolicy",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("write", "Write/Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("upload", "Upload"),
                    ("download", "Download"),
                    ("encrypt", "Encrypt"),
                    ("decrypt", "Decrypt"),
                    ("*", "All Actions"),
                ],
                help_text="Action this policy permits/denies",
                max_length=50,
            ),
        ),
    ]
