# Generated by Django 5.2.6 on 2026-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0027_alter_accesspolicy_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpublickey",
            name="encrypted_pqc_sk_primary",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded string: [IV (12 bytes)] + [Ciphertext of Secret Key encrypted with WebAuthn PRF]",
                null=True,
            ),
        ),
    ]
