# Generated by Django 5.2.6 on 2026-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0028_alter_userpublickey_encrypted_pqc_sk_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpublickey",
            name="credential_id",
            field=models.CharField(
                blank=True,
                help_text="WebAuthn Credential ID (Base64) for cross-browser PRF discovery on the same device",
                max_length=512,
                null=True,
            ),
        ),
    ]
