# Generated by Django 5.2.6 on 2026-07-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_access", "0029_userpublickey_credential_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="abe_scheme",
            field=models.CharField(
                default="ac17",
                help_text="ABE scheme used to encrypt this file (ac17, tkn20)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="accesspolicy",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "👁️ View"),
                    ("write", "✏️ Create"),
                    ("update", "📝 Update"),
                    ("delete", "🗑️ Delete"),
                    ("upload", "⬆️ Upload"),
                    ("download", "⬇️ Download"),
                    ("encrypt", "🔒 Encryption"),
                    ("decrypt", "🔓 Decrypt"),
                    ("*", "⭐ All actions (*)"),
                ],
                help_text="Action this policy permits/denies",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="accesspolicy",
            name="effect",
            field=models.CharField(
                choices=[("allow", "✅ Allow"), ("deny", "❌ Deny")],
                default="allow",
                help_text="Whether to allow or deny this access",
                max_length=10,
            ),
        ),
    ]
